# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cartesian Bio
email: info@cartesian.bio
admin_email: steve@cartesian.bio
description: > # this means to ignore newlines until "baseurl:"
  We help treat hard-to-treat diseases.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cartesian.bio" # the base hostname & protocol for your site

google_api_key: '772140540805-5iim4e7thijd0r8dl68omgq4gs93lckh.apps.googleusercontent.com'
# Build settings
markdown: kramdown
